In [17]:
import pandas as pd
import marimo as mo
import numpy as np
import seaborn as sns
import matplotlib as plt
import datetime as dl

df = pd.read_excel(R"C:\Users\TAJ\Desktop\world_economic_report\WorldBank.xlsx").rename({"Country Name": "Country"}, axis=1)

In [3]:
pip install marimo

Requirement already satisfied: marimo in c:\users\taj\anaconda3\lib\site-packages (0.18.4)
Requirement already satisfied: click<9,>=8.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (8.1.7)
Requirement already satisfied: jedi>=0.18.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (0.18.1)
Requirement already satisfied: markdown<4,>=3.6 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (3.10)
Requirement already satisfied: pymdown-extensions<11,>=10.15 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (10.20)
Requirement already satisfied: pygments<3,>=2.19 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (2.19.2)
Requirement already satisfied: tomlkit>=0.12.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (0.13.3)
Requirement already satisfied: pyyaml>=6.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (6.0.1)
Requirement already satisfied: uvicorn>=0.22.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (0.40.0)
Requirement already satisfied: starlette!=0.36.0,>=0.35.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (0.50.0)
Requirement already satisfied: websockets>=14.2.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (15.0.1)
Requirement already satisfied: loro>=1.5.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (1.10.3)
Requirement already satisfied: docutils>=0.16.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (0.18.1)
Requirement already satisfied: psutil>=5.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (5.9.0)
Requirement already satisfied: itsdangerous>=2.0.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (2.2.0)
Requirement already satisfied: narwhals>=2.0.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (2.0.1)
Requirement already satisfied: packaging in c:\users\taj\anaconda3\lib\site-packages (from marimo) (23.2)
Requirement already satisfied: msgspec>=0.20.0 in c:\users\taj\anaconda3\lib\site-packages (from marimo) (0.20.0)
Requirement already satisfied: colorama in c:\users\taj\anaconda3\lib\site-packages (from click<9,>=8.0->marimo) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\taj\anaconda3\lib\site-packages (from jedi>=0.18.0->marimo) (0.8.3)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\taj\anaconda3\lib\site-packages (from starlette!=0.36.0,>=0.35.0->marimo) (4.2.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\taj\anaconda3\lib\site-packages (from starlette!=0.36.0,>=0.35.0->marimo) (4.11.0)
Requirement already satisfied: h11>=0.8 in c:\users\taj\anaconda3\lib\site-packages (from uvicorn>=0.22.0->marimo) (0.14.0)
Requirement already satisfied: idna>=2.8 in c:\users\taj\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette!=0.36.0,>=0.35.0->marimo) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\taj\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette!=0.36.0,>=0.35.0->marimo) (1.3.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
df.head()

,Country,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,NaN,NaN,NaN,1.936300e+10,520.897,NaN,47.9,NaN,56.9378,1.542
1,Afghanistan,AFG,South Asia,Low income,2017,33.211,6.575,NaN,2.019180e+10,556.302,13.50,49.5,64.130,55.5960,1.559
2,Afghanistan,AFG,South Asia,Low income,2016,33.981,6.742,NaN,1.936260e+10,547.228,11.20,51.2,63.763,54.1971,1.634
3,Afghanistan,AFG,South Asia,Low income,2015,34.809,6.929,NaN,1.990710e+10,578.466,8.26,53.1,63.377,52.7121,1.679
4,Afghanistan,AFG,South Asia,Low income,2014,35.706,7.141,NaN,2.048490e+10,613.856,7.00,55.1,62.966,51.1148,1.735

In [5]:
display(df.describe())

,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
count,12449.00000,11440.000000,11416.000000,5848.000000,9.578000e+03,9575.000000,5064.000000,9984.000000,11176.000000,11845.000000,5208.000000
mean,1989.00000,28.643276,10.588539,3175.294686,1.700740e+11,8231.812259,23.334471,51.704437,64.044692,318.861370,8.295079
std,17.03007,13.131893,5.489382,4467.139298,8.979866e+11,16173.539954,28.319388,46.131039,11.491087,1593.406041,6.290703
min,1960.00000,6.900000,1.127000,0.000000,8.824450e+06,34.790600,0.000000,1.400000,18.907000,0.098625,0.140000
25%,1974.00000,16.600000,6.863750,390.385750,1.393010e+09,513.145500,0.594949,14.475000,55.917750,19.783400,3.687000
50%,1989.00000,27.545500,9.200000,1541.895000,7.275305e+09,1852.810000,8.406225,37.000000,67.276000,64.007500,6.775000
75%,2004.00000,40.881250,12.687000,4313.767500,4.857782e+10,7774.565000,41.295950,78.200000,72.692250,144.823000,11.212250
max,2018.00000,58.227000,54.444000,54799.200000,2.050000e+13,189171.000000,100.000000,279.400000,85.417100,21389.100000,37.940000

In [6]:
# sns.histplot("df[Country Name]")
df[['Country Name','Region','IncomeGroup']]

      Country Name              Region IncomeGroup
0      Afghanistan          South Asia  Low income
1      Afghanistan          South Asia  Low income
2      Afghanistan          South Asia  Low income
3      Afghanistan          South Asia  Low income
4      Afghanistan          South Asia  Low income
...            ...                 ...         ...
12444     Zimbabwe  Sub-Saharan Africa  Low income
12445     Zimbabwe  Sub-Saharan Africa  Low income
12446     Zimbabwe  Sub-Saharan Africa  Low income
12447     Zimbabwe  Sub-Saharan Africa  Low income
12448     Zimbabwe  Sub-Saharan Africa  Low income

[12449 rows x 3 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12449 entries, 0 to 12448
Data columns (total 15 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Country Name                                                  12449 non-null  object
 1   Country Code                                                  12449 non-null  object
 2   Region                                                        12449 non-null  object
 3   IncomeGroup                                                   12449 non-null  object
 4   Year                                                          12449 non-null  int64
 5   Birth rate, crude (per 1,000 people)                          11440 non-null  float64
 6   Death rate, crude (per 1,000 people)                          11416 non-null  float64
 7   Electric power consumption (kWh per capita)                   5848 non-null   float64
 8   GDP (USD)                                                     9578 non-null   float64
 9   GDP per capita (USD)                                          9575 non-null   float64
 10  Individuals using the Internet (% of population)              5064 non-null   float64
 11  Infant mortality rate (per 1,000 live births)                 9984 non-null   float64
 12  Life expectancy at birth (years)                              11176 non-null  float64
 13  Population density (people per sq. km of land area)           11845 non-null  float64
 14  Unemployment (% of total labor force) (modeled ILO estimate)  5208 non-null   float64
dtypes: float64(10), int64(1), object(4)
memory usage: 1.4+ MB

In [8]:
df[df.isna().any(axis=1)]

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,NaN,NaN,NaN,1.936300e+10,520.897,NaN,47.9,NaN,56.9378,1.542
1,Afghanistan,AFG,South Asia,Low income,2017,33.211,6.575,NaN,2.019180e+10,556.302,13.50,49.5,64.130,55.5960,1.559
2,Afghanistan,AFG,South Asia,Low income,2016,33.981,6.742,NaN,1.936260e+10,547.228,11.20,51.2,63.763,54.1971,1.634
3,Afghanistan,AFG,South Asia,Low income,2015,34.809,6.929,NaN,1.990710e+10,578.466,8.26,53.1,63.377,52.7121,1.679
4,Afghanistan,AFG,South Asia,Low income,2014,35.706,7.141,NaN,2.048490e+10,613.856,7.00,55.1,62.966,51.1148,1.735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770,13.083,NaN,1.217138e+09,281.558,NaN,83.2,54.849,11.1745,NaN
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876,13.419,NaN,1.159512e+09,277.480,NaN,85.7,54.403,10.8019,NaN
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950,13.762,NaN,1.117602e+09,276.689,NaN,88.1,53.946,10.4413,NaN
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988,14.104,NaN,1.096647e+09,280.829,NaN,90.5,53.483,10.0944,NaN
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996,14.441,NaN,1.052990e+09,278.814,NaN,92.8,53.019,NaN,NaN

In [12]:
# import matplotlib.pyplot as plt
# plt.hist(df['Region'])

In [11]:
# category_counts = df['Region'].value_counts()
# plt.bar(category_counts.index, category_counts.values)
# plt.show()

In [ ]:
# profile and QA the data Objective One

In [21]:
df["Population (M)"] = (df["GDP (USD)"] / df["GDP per capita (USD)"])
df

,Country,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate),Population (M)
0,Afghanistan,AFG,South Asia,Low income,2018,NaN,NaN,NaN,1.936300e+10,520.897,NaN,47.9,NaN,56.9378,1.542,3.717242e+07
1,Afghanistan,AFG,South Asia,Low income,2017,33.211,6.575,NaN,2.019180e+10,556.302,13.50,49.5,64.130,55.5960,1.559,3.629647e+07
2,Afghanistan,AFG,South Asia,Low income,2016,33.981,6.742,NaN,1.936260e+10,547.228,11.20,51.2,63.763,54.1971,1.634,3.538306e+07
3,Afghanistan,AFG,South Asia,Low income,2015,34.809,6.929,NaN,1.990710e+10,578.466,8.26,53.1,63.377,52.7121,1.679,3.441360e+07
4,Afghanistan,AFG,South Asia,Low income,2014,35.706,7.141,NaN,2.048490e+10,613.856,7.00,55.1,62.966,51.1148,1.735,3.337086e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770,13.083,NaN,1.217138e+09,281.558,NaN,83.2,54.849,11.1745,NaN,4.322868e+06
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876,13.419,NaN,1.159512e+09,277.480,NaN,85.7,54.403,10.8019,NaN,4.178722e+06
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950,13.762,NaN,1.117602e+09,276.689,NaN,88.1,53.946,10.4413,NaN,4.039198e+06
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988,14.104,NaN,1.096647e+09,280.829,NaN,90.5,53.483,10.0944,NaN,3.905033e+06
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996,14.441,NaN,1.052990e+09,278.814,NaN,92.8,53.019,NaN,NaN,3.776677e+06